version: '3.0'
services:
    frontend:
        container_name: frontend
        build: 
          context: .
        image: frontend
        ports:
            - "8080:8080"
networks:
  default:
    external:
      name: wongnokproject