version: '2.0'
services:
    frontend:
        container_name: frontend
        build: .
        image: frontend
        ports:
            - "8080:8080"
networks:
  default:
    external:
      name: wongnokproject