version: '2.2'
services:
    frontend:
        container_name: frontend
        build: .
        image: ghcr.io/chicky0/int222-frontend:latest
        ports:
            - "8080:8080"
networks:
  default:
    external:
      name: wongnokproject